apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth
  namespace: lighthouse
spec:
  selector:
    matchLabels:
      app: geth
  serviceName: geth
  replicas: 1
  template:
    metadata:
      labels:
        app: geth
    spec:
      containers:
      - name: client-go
        image: ethereum/client-go:stable
        ports:
        - containerPort: 8551
          name: authrpc
          protocol: TCP
        - containerPort: 30303
          name: listener
          protocol: TCP
        - containerPort: 30303
          name: discovery
          protocol: UDP
        volumeMounts:
        - name: geth-data
          mountPath: /root/data
        - name: jwt-token
          mountPath: /root/jwttoken/jwtsecret.hex
          subPath: jwtsecret.hex
        command:
        - geth
        - --sepolia
        - --datadir=/root/data/.ethereum
        - --datadir.ancient=/root/data/ancient-data
        - --http
        - --http.addr=0.0.0.0
        - --http.vhosts=*
        - --http.api=eth,net
        - --ipcdisable
        - --authrpc.addr=0.0.0.0
        - --authrpc.port=8551
        - --authrpc.vhosts=*
        - --authrpc.jwtsecret=/root/jwttoken/jwtsecret.hex
      volumes:
      - name: jwt-token
        secret:
          secretName: jwt-token
  volumeClaimTemplates:
  - metadata:
      name: geth-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-ssd-storage"
      resources:
        requests:
          storage: 1510Gi

---
apiVersion: v1
kind: Service
metadata:
  name: geth-exposed
  namespace: lighthouse
spec:
  selector:
    app: geth
  type: NodePort
  ports:
  - name: listener
    port: 30303
    nodePort: 30303
    targetPort: 30303
    protocol: TCP
  - name: discovery
    port: 30303
    nodePort: 30303
    targetPort: 30303
    protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: geth-authrpc
  namespace: lighthouse
spec:
  selector:
    app: geth
  type: ClusterIP
  ports:
  - name: authrpc
    port: 8551
    targetPort: 8551
    protocol: TCP
